#!/bin/bash

# check if dialog is installed and if its not, install it
REQUIRED_PKG="dialog"
PKG_OK=$(dpkg-query -W --showformat='${Status}\n' $REQUIRED_PKG|grep "install ok installed")
echo Checking for $REQUIRED_PKG: $PKG_OK
if [ "" = "$PKG_OK" ]; then
  echo "Please Wait"
  echo "No $REQUIRED_PKG. Setting up $REQUIRED_PKG."
  sudo apt-get --yes install $REQUIRED_PKG
fi

#detect the ldap domain
ldap_domain=$(ldapsearch -LLL -x -b "" -s base namingContexts | grep "namingContexts" | awk '{print $2}')

makegldif() {
# GROUP LDIF EXAMPLE
    cat << EOF > grup.ldif
# Es pot fer servir un dels 2 DN, un per posar-lo dins a una Unitat Organitzativa i l'altre no.
# dn: cn=Grup,ou=UnitatOrganitzativa,$ldap_domain
dn: cn=Grup,$ldap_domain
objectClass: top
objectClass: posixGroup
gidNumber: 2000
cn: Grup
EOF
sudo chmod 777 grup.ldif
}

makeuldfif() {
    cat << EOF > usuari.ldif
# Es pot fer servir un dels 2 DN, un per posar-lo dins a una Unitat Organitzativa i l'altre no.
# dn: uid=Usuari,ou=UnitatOrganitzativa,$ldap_domain
dn: uid=Usuari,$ldap_domain
objectClass: top
objectClass: posixAccount
objectClass: inetOrgPerson
objectClass: person
cn: Usuari
uid: Usuari
uidNumber 2000
#gidNumber: 2000
#homeDirectory: /home/usuari
#loginShell: /bin/bash
#sn: Cognom
userPassword: caput
EOF
sudo chmod 777 usuari.ldif
}

makeouldif() {
  sudo  cat << EOF > ou.ldif
# Per Afegir aquesta entrada, fes: sudo ldapadd -x -D cn=admin,$ldap_domain
dn: ou=UnitatOrganitzativa,$ldap_domain
objectClass: top
objectClass: organizationalUnit
ou: UnitatOrganitzativa
EOF
sudo chmod 777 ou.ldif
}

createxampleldif() {
    makeouldif
    makeuldfif
    makegldif
}


configure_ldapscripts(){
    cat << EOF > /etc/ldapscripts/ldapscripts.conf
#CONFIG FILE FOR LDAPSCRIPTS - GENERATED BY LDAP-CONFIGURATOR v1.5, © 2024 ShadowOfPripyat™


# LDAP server
# DEBIAN: value from /etc/nslcd.conf (uri) is used.
SERVER="ldap://localhost:389"

# Suffixes
# DEBIAN: values from /etc/nslcd.conf (base maps) are used.
SUFFIX="$ldap_domain" # Global suffix
GSUFFIX="ou=Grups"         # Groups   ou (just under $SUFFIX)
USUFFIX="ou=Usuaris"       # Users    ou (just under $SUFFIX)
MSUFFIX="ou=Maquines"      # Machines ou (just under $SUFFIX)

# Simple authentication parameters
# The following BIND* parameters are ignored if SASLAUTH is set
BINDDN="cn=admin,$ldap_domain"
# The following file contains the raw password of the BINDDN
# Create it with something like : echo -n 'secret' > $BINDPWDFILE
# WARNING !!!! Be careful not to make this file world-readable
BINDPWDFILE="/etc/ldapscripts/ldapscripts.passwd"
# For older versions of OpenLDAP, it is still possible to use
# unsecure command-line passwords by defining the following option
# AND commenting the previous one (BINDPWDFILE takes precedence)
#BINDPWD="secret"

# Start with these IDs *if no entry found in LDAP*
GIDSTART="10000" # Group ID
UIDSTART="10000" # User ID
MIDSTART="20000" # Machine ID

# Group membership management
# ObjectCLass used for groups
# Possible values : posixGroup, groupOfNames, groupOfUniqueNames (case-sensitive !)
GCLASS="posixGroup"   # Leave "posixGroup" here if not sure !
# When using  groupOfNames or groupOfUniqueNames, creating a group requires an initial
# member. Specify it below, you will be able to remove it once groups are populated.
#GDUMMYMEMBER="uid=dummy,$USUFFIX,$SUFFIX"

# User properties
# DEBIAN: values from /etc/adduser.conf are used.
USHELL="/bin/sh"
UHOMES="/home/%u"     # You may use %u for username here
CREATEHOMES="no"      # Create home directories and set rights ?
HOMESKEL="/etc/skel"  # Directory where the skeleton files are located. Ignored if undefined or nonexistant.
HOMEPERMS="755"       # Default permissions for home directories

# User passwords generation
# Command-line used to generate a password for added users.
# You may use %u for username here ; special value "<ask>" will ask for a password interactively
# WARNING    !!!! This is evaluated, everything specified here will be run !
# WARNING(2) !!!! Some systems (Linux) use a blocking /dev/random (waiting for enough entropy).
#                 In this case, consider using /dev/urandom instead.
#PASSWORDGEN="cat /dev/random | LC_ALL=C tr -dc 'a-zA-Z0-9' | head -c8"
#PASSWORDGEN="pwgen"
#PASSWORDGEN="echo changeme"
#PASSWORDGEN="echo %u"
#PASSWORDGEN="<ask>"
PASSWORDGEN="pwgen"

# User passwords recording
# you can keep trace of generated passwords setting PASSWORDFILE and RECORDPASSWORDS
# (useful when performing a massive creation / net rpc vampire)
# WARNING !!!! DO NOT FORGET TO DELETE THE GENERATED FILE WHEN DONE !
# WARNING !!!! DO NOT FORGET TO TURN OFF RECORDING WHEN DONE !
RECORDPASSWORDS="no"
PASSWORDFILE="/var/log/ldapscripts_passwd.log"

# Where to log : local file and/or syslog
LOGTOFILE="yes"
LOGFILE="/var/log/ldapscripts.log"
LOGTOSYSLOG="no"
SYSLOGFACILITY="local4"
SYSLOGLEVEL="info"

# Temporary folder
#TMPDIR="/tmp"

# OpenLDAP client commands
LDAPSEARCHBIN="/usr/bin/ldapsearch"
LDAPADDBIN="/usr/bin/ldapadd"
LDAPDELETEBIN="/usr/bin/ldapdelete"
LDAPMODIFYBIN="/usr/bin/ldapmodify"
LDAPMODRDNBIN="/usr/bin/ldapmodrdn"
LDAPPASSWDBIN="/usr/bin/ldappasswd"

# OpenLDAP client common additional options
# This allows for adding more configuration options to the OpenLDAP clients, e.g. '-ZZ' to enforce TLS
#LDAPBINOPTS="-ZZ"

# OpenLDAP ldapsearch-specific additional options
# The following option disables long-line wrapping (which makes the scripts bug
# when handling long lines). The option was introduced in OpenLDAP 2.4.24, so
# comment it if you are using OpenLDAP < 2.4.24.
LDAPSEARCHOPTS="-o ldif-wrap=no"
# And here is an example to activate paged results
#LDAPSEARCHOPTS="-E pr=500/noprompt"

# Character set conversion : $ICONVCHAR <-> UTF-8
# Comment ICONVBIN to disable UTF-8 conversion
#ICONVBIN="/usr/bin/iconv"
#ICONVCHAR="ISO-8859-15"

# Getent command to use - choose the ones used
# on your system. Leave blank or comment for auto-guess.
# GNU/Linux
#GETENTPWCMD="getent passwd"
#GETENTGRCMD="getent group"
# Auto
GETENTPWCMD=""
GETENTGRCMD=""

# You can specify custom LDIF templates here
# Leave empty to use default templates
# See *.template.sample for default templates
#GTEMPLATE="/path/to/ldapaddgroup.template"
#UTEMPLATE="/path/to/ldapadduser.template"
#MTEMPLATE="/path/to/ldapaddmachine.template"
GTEMPLATE=""
UTEMPLATE=""
MTEMPLATE=""
EOF
}


#-------------check-if-packages-are-installed-----------------------
pkg1=$(
  # Check if is installed
  PKG_NAME1="slapd"
  # PKG_OKY6=$(dpkg-query -W --showformat='${Package}\n' $PKG_NAME2|grep "PKG_NAME2" 2> /dev/null)
  if dpkg-query -W --showformat='${Status}\n' $PKG_NAME1 2>/dev/null |grep "install ok installed" > /dev/null; then
    echo "$PKG_NAME1 is Installed"
  else
    echo "$PKG_NAME1 is not installed."
  fi
)

pkg2=$(
  PKG_NAME2="ldap-utils"
  if dpkg-query -W --showformat='${Status}\n' $PKG_NAME2 2>/dev/null |grep "install ok installed" > /dev/null; then
    echo "$PKG_NAME2 is Installed"
  else
    echo "$PKG_NAME2 is not installed."
  fi
)

pkg3=$(
PKG_NAME3="ldapscripts"
  if dpkg-query -W --showformat='${Status}\n' $PKG_NAME3 2>/dev/null |grep "install ok installed" > /dev/null; then
    echo "$PKG_NAME3 is Installed"
  else
    echo "$PKG_NAME3 is not installed."
  fi
)

pkg4=$(
  PKG_NAME4="ldap-account-manager"
  if dpkg-query -W --showformat='${Status}\n' $PKG_NAME4 2>/dev/null |grep "install ok installed" > /dev/null; then
    echo "$PKG_NAME4 is Installed"
  else
    echo "$PKG_NAME4 is not installed."
  fi
)


#+++++++++++++set+up+main++Organizational+Units+++++++++++++++++++++++++++++++++++++++++++++++++++++

setup_main_ous(){
  cat << EOF > MAIN-OUS.ldif
dn: ou=Usuaris,$ldap_domain
objectClass: organizationalUnit
objectClass: top
ou: Usuaris

dn: ou=Grups,$ldap_domain
objectClass: organizationalUnit
objectClass: top
ou: Grups

dn: ou=Maquines,$ldap_domain
objectClass: organizationalUnit
objectClass: top
ou: Maquines
EOF
printf "\n\nA continuació es demanarà la contrasenya del teu domini LDAP\nPer afegir les OU principals de LDAPSCRIPTS:\n\n"
sudo ldapadd -f MAIN-OUS.ldif -D cn=admin,$ldap_domain -xW
}

#´´´´´´´´´ldap´´password´´stuff´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´´
#create temp file for ldap password
ldapscriptspasswd() {
    # Prompt user for secret word using dialog
    # secret=$(dialog --clear --title "Set LDAP secret" \
    #     --inputbox "Enter your LDAP password:" 10 30 2>&1 >/dev/tty) #old method
    exec 3>&1;
    secret=$(dialog --clear --title "Configure LDAPSCRIPTS" --inputbox "Introdueix la contrasenya de LDAP" 0 0 2>&1 1>&3);
    exec 3>&-;

    # Check if dialog was cancelled or user didn't input anything
    if [ $? -ne 0 ] || [ -z "$secret" ]; then
        echo "Operation cancelled. Maybe you didnt write a password?"
        return
    fi

    # Update the LDAP password file with the secret
    filtersecret=$(echo "$secret" | tr -d '\n')  # Remove newline character (sanitize)
    echo -n "$filtersecret" | tr -d '\n' > /etc/ldapscripts/ldapscripts.passwd
    chmod 400 /etc/ldapscripts/ldapscripts.passwd
    echo "Secret word '$secret' successfully set in /etc/ldapscripts/ldapscripts.passwd"
}


 doallabove(){
      #packages
      sudo apt update && sudo apt install -y slapd ldap-utils ldapscripts ldap-account-manager
      result=$(echo && echo "S'han instalat tots els paquets correctament")
      display_result "Instalació de Paquets LDAP"
      #set-domain
      sudo dpkg-reconfigure slapd
      result=$(echo "has reconfigurat el domini LDAP (slapd)".)
      display_result "Reconfiguració del Domini"
      #create-ldif-with-actual-domain
      createxampleldif
      result=$(echo "s'han creat els fitxers ldif d'exemple".)
      display_result "Make LDIF Examples"
      #configure-ldapscirpts
      configure_ldapscripts
      ldapscriptspasswd
      setup_main_ous
      result=$(printf "s'ha creat 'ldapscripts.conf' amb el domini actual \nS'han creat les Unitats Organitzatives Principals \nS'ha establert la contrasenya de LDAP a ldapscripts.passwd  ")
      display_result "Configuració de ldapscripts"
 }
#--------------------------------------------------START--GRAPHICAL--INTERFACE------------------------------------------------------#

DIALOG_CANCEL=1
DIALOG_ESC=255
HEIGHT=0
WIDTH=0

editfilesmenu(){
    exec 3>&1
  filesmenu=$(dialog \
    --backtitle "LDAP CONFIGURATOR v1 GRAPHICAL-EDITION | VIEW AND EDIT LDAP FILES" \
    --title "VIEW AND EDIT LDAP FILES" \
    --clear \
    --cancel-label "Back" \
    --menu "In this menu you can choose to open an LDAP-related file with NANO.  \n \n Please select:" $HEIGHT $WIDTH 6 \
    "1" "ldapscripts.conf (/etc/ldapscripts/)" \
    "2" "ldapscripts.passwd (/etc/ldapscripts/)" \
    "3" "netplan" \
    "4" "Funció extra (No Implementada)" \
    2>&1 1>&3)
  exit_status=$?
  exec 3>&-

  case $filesmenu in
    1 )
      clear
      sudo nano /etc/ldapscripts/ldapscripts.conf
      result=$(echo "Has tornat!")
      display_result "LDAP CONFIGURATOR"
      ;;
    2 )
      clear
      sudo nano /etc/ldapscripts/ldapscripts.passwd
      result=$(echo "Has tornat!")
      display_result "LDAP CONFIGURATOR"
      ;;
    3 )
      result=$(echo "No hi ha res a veure de moment.")
      display_result "Funció no implementada"
      ;;
    4 )
      result=$(echo "No hi ha res a veure de moment.")
      display_result "Funció no implementada"
      ;;
  esac
}

otheroptionsmenu(){
    exec 3>&1
  altmenu=$(dialog \
    --backtitle "LDAP CONFIGURATOR v1 GRAPHICAL-EDITION | MORE OPTIONS" \
    --title "OTHER OPTIONS" \
    --clear \
    --cancel-label "Back" \
    --menu "This menu shows alternative options.  \n \n Please select:" $HEIGHT $WIDTH 6 \
    "1" "PURGAR tots els paquets ldap" \
    "2" "RE-INSTALAR tots els paquets ldap" \
    "3" "Editar Fitxer..." \
    "4" "Funció extra (No Implementada)" \
    2>&1 1>&3)
  exit_status=$?
  exec 3>&-

  case $altmenu in
    1 )
      clear
      sudo apt purge -y slapd ldap-utils ldapscripts ldap-account-manager
      result=$(echo && echo "S'han DESINSTALAT tots els paquets LDAP.")
      display_result "Eliminació de Paquets LDAP"
      ;;
    2 )
      clear
      sudo apt purge -y slapd ldap-utils ldapscripts ldap-account-manager && sudo apt install -y slapd ldap-utils ldapscripts ldap-account-manager
      result=$(echo && echo "S'han RE-INSTALAT tots els paquets LDAP.")
      display_result "RE-INSTALACIÓ de Paquets LDAP"
      ;;
    3 )
      editfilesmenu
      ;;
    4 )
      result=$(echo "No hi ha res a veure de moment.")
      display_result "Funció no implementada"
      ;;
  esac
}



display_result() {
  dialog --title "$1" \
    --no-collapse \
    --msgbox "$result" 0 0
}

inputwindow() {
  # show an inputbox
dialog --title "Inputbox - To take input from you" \
--backtitle "Linux Shell Script Tutorial Example" \
--inputbox "Enter your LDAP password " 8 60 2>$OUTPUT
}

while true; do
  exec 3>&1
  selection=$(dialog \
    --backtitle "LDAP CONFIGURATOR v1 GRAPHICAL-EDITION" \
    --title "LDAP CONFIGURATOR - $ldap_domain" \
    --clear \
    --cancel-label "Exit" \
    --menu "INFO: \n $pkg1 \n $pkg2 \n $pkg3 \n $pkg4 \n  \n \n Please select:" $HEIGHT $WIDTH 6 \
    "1" "Instalar tots els paquets ldap" \
    "2" "Reconfigurar slapd i canviar el nom del domini" \
    "3" "Crear Fitxers .LDIF d'exemple" \
    "4" "Configurar LDAPSCRIPTS" \
    "5" "Més opcions..." \
    "6" "Fer TOT lo llistat a dalt" \
    2>&1 1>&3)
  exit_status=$?
  exec 3>&-
  case $exit_status in
    $DIALOG_CANCEL)
      clear
      echo "Program terminated."
      exit
      ;;
    $DIALOG_ESC)
      clear
      echo "Program aborted." >&2
      exit 1
      ;;
  esac
  case $selection in
    1 )
      sudo apt update && sudo apt install -y slapd ldap-utils ldapscripts ldap-account-manager
      result=$(echo && echo "S'han instalat tots els paquets correctament")
      display_result "Instalació de Paquets LDAP"
      ;;
    2 )
      sudo dpkg-reconfigure slapd
      result=$(echo "has reconfigurat el domini LDAP (slapd)".)
      display_result "Reconfiguració del Domini"
      ;;
    3 )
      createxampleldif
      result=$(echo "s'han creat els fitxers ldif d'exemple".)
      display_result "Make LDIF Examples"
      ;;
    4 )
      configure_ldapscripts
      ldapscriptspasswd
      setup_main_ous
      result=$(printf "- s'ha creat 'ldapscripts.conf' amb el domini actual \n\n - S'han creat les Unitats Organitzatives Principals \n\n - S'ha establert la contrasenya de LDAP a ldapscripts.passwd")
      display_result "Configuració de ldapscripts"
      ;;
    5 )
      otheroptionsmenu
      ;;
    6 )
      doallabove
      ;;
    # 7 )
    #   if [[ $(id -u) -eq 0 ]]; then
    #     result=$(du -sh /home/* 2> /dev/null)
    #     display_result "Home Space Utilization (All Users)"
    #   else
    #     result=$(du -sh $HOME 2> /dev/null)
    #     display_result "Home Space Utilization ($USER)"
    #   fi
    #   ;;
  esac
done
#-----------------------------------------------------END--GRAPHICAL--INTERFACE------------------------------------------------------#
